/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginRedirectorImport } from './routes/login-redirector'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ActivateAccountImport } from './routes/activate-account'
import { Route as IndexImport } from './routes/index'
import { Route as PasswordResetCodeIndexImport } from './routes/password-reset-code/index'
import { Route as PasswordResetCodeVerifyImport } from './routes/password-reset-code/verify'
import { Route as PasswordResetCodeSuccessImport } from './routes/password-reset-code/success'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRedirectorRoute = LoginRedirectorImport.update({
  id: '/login-redirector',
  path: '/login-redirector',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ActivateAccountRoute = ActivateAccountImport.update({
  id: '/activate-account',
  path: '/activate-account',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PasswordResetCodeIndexRoute = PasswordResetCodeIndexImport.update({
  id: '/password-reset-code/',
  path: '/password-reset-code/',
  getParentRoute: () => rootRoute,
} as any)

const PasswordResetCodeVerifyRoute = PasswordResetCodeVerifyImport.update({
  id: '/password-reset-code/verify',
  path: '/password-reset-code/verify',
  getParentRoute: () => rootRoute,
} as any)

const PasswordResetCodeSuccessRoute = PasswordResetCodeSuccessImport.update({
  id: '/password-reset-code/success',
  path: '/password-reset-code/success',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/activate-account': {
      id: '/activate-account'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof ActivateAccountImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login-redirector': {
      id: '/login-redirector'
      path: '/login-redirector'
      fullPath: '/login-redirector'
      preLoaderRoute: typeof LoginRedirectorImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/password-reset-code/success': {
      id: '/password-reset-code/success'
      path: '/password-reset-code/success'
      fullPath: '/password-reset-code/success'
      preLoaderRoute: typeof PasswordResetCodeSuccessImport
      parentRoute: typeof rootRoute
    }
    '/password-reset-code/verify': {
      id: '/password-reset-code/verify'
      path: '/password-reset-code/verify'
      fullPath: '/password-reset-code/verify'
      preLoaderRoute: typeof PasswordResetCodeVerifyImport
      parentRoute: typeof rootRoute
    }
    '/password-reset-code/': {
      id: '/password-reset-code/'
      path: '/password-reset-code'
      fullPath: '/password-reset-code'
      preLoaderRoute: typeof PasswordResetCodeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate-account': typeof ActivateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/login-redirector': typeof LoginRedirectorRoute
  '/signup': typeof SignupRoute
  '/password-reset-code/success': typeof PasswordResetCodeSuccessRoute
  '/password-reset-code/verify': typeof PasswordResetCodeVerifyRoute
  '/password-reset-code': typeof PasswordResetCodeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate-account': typeof ActivateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/login-redirector': typeof LoginRedirectorRoute
  '/signup': typeof SignupRoute
  '/password-reset-code/success': typeof PasswordResetCodeSuccessRoute
  '/password-reset-code/verify': typeof PasswordResetCodeVerifyRoute
  '/password-reset-code': typeof PasswordResetCodeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/activate-account': typeof ActivateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/login-redirector': typeof LoginRedirectorRoute
  '/signup': typeof SignupRoute
  '/password-reset-code/success': typeof PasswordResetCodeSuccessRoute
  '/password-reset-code/verify': typeof PasswordResetCodeVerifyRoute
  '/password-reset-code/': typeof PasswordResetCodeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate-account'
    | '/dashboard'
    | '/login'
    | '/login-redirector'
    | '/signup'
    | '/password-reset-code/success'
    | '/password-reset-code/verify'
    | '/password-reset-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate-account'
    | '/dashboard'
    | '/login'
    | '/login-redirector'
    | '/signup'
    | '/password-reset-code/success'
    | '/password-reset-code/verify'
    | '/password-reset-code'
  id:
    | '__root__'
    | '/'
    | '/activate-account'
    | '/dashboard'
    | '/login'
    | '/login-redirector'
    | '/signup'
    | '/password-reset-code/success'
    | '/password-reset-code/verify'
    | '/password-reset-code/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivateAccountRoute: typeof ActivateAccountRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LoginRedirectorRoute: typeof LoginRedirectorRoute
  SignupRoute: typeof SignupRoute
  PasswordResetCodeSuccessRoute: typeof PasswordResetCodeSuccessRoute
  PasswordResetCodeVerifyRoute: typeof PasswordResetCodeVerifyRoute
  PasswordResetCodeIndexRoute: typeof PasswordResetCodeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivateAccountRoute: ActivateAccountRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LoginRedirectorRoute: LoginRedirectorRoute,
  SignupRoute: SignupRoute,
  PasswordResetCodeSuccessRoute: PasswordResetCodeSuccessRoute,
  PasswordResetCodeVerifyRoute: PasswordResetCodeVerifyRoute,
  PasswordResetCodeIndexRoute: PasswordResetCodeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/activate-account",
        "/dashboard",
        "/login",
        "/login-redirector",
        "/signup",
        "/password-reset-code/success",
        "/password-reset-code/verify",
        "/password-reset-code/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/activate-account": {
      "filePath": "activate-account.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/login-redirector": {
      "filePath": "login-redirector.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/password-reset-code/success": {
      "filePath": "password-reset-code/success.tsx"
    },
    "/password-reset-code/verify": {
      "filePath": "password-reset-code/verify.tsx"
    },
    "/password-reset-code/": {
      "filePath": "password-reset-code/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
